## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
from sklearn.model_selection import train_test_split, KFold
index1 = np.where(y == 0)
X_train1, X_test1, y_train1, y_test1 = train_test_split(X[index1], y[index1], test_size=10, random_state=42)
index2 = np.where(y == 1)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X[index2], y[index2], test_size=10, random_state=42)
X_train = np.concatenate((X_train1, X_train2), axis=0)
X_test = np.concatenate((X_test1, X_test2), axis=0)
y_train = np.concatenate((y_train1, y_train2), axis=0)
y_test = np.concatenate((y_test1, y_test2), axis=0)
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [4]:
from sklearn.model_selection import train_test_split

y0 = np.where(y == 0)
y1 = np.where(y == 1)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X[y0], y[y0], test_size=10)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X[y1], y[y1], test_size=10)

print(f'y_test_1={y_test_1}')
print(f'y_test_2={y_test_2}')

X_train = np.append(X_train_1, X_train_2)
X_test = np.append(X_test_1, X_test_2)
y_train = np.append(y_train_1, y_train_2)
y_test = np.append(y_test_1, y_test_2)


y_test_1=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
y_test_2=[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### API
sklearn.model_selection.[train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html#sklearn.model_selection.train_test_split)

In [5]:
print(f'X_train.shape={X_train.shape}')
print(f'X_test.shape={X_test.shape}')
print(f'y_train.shape={y_train.shape}')
print(f'y_test.shape={y_test.shape}')

X_train.shape=(900,)
X_test.shape=(100,)
y_train.shape=(180,)
y_test.shape=(20,)


In [6]:
print(y_test)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
